# Generated by Django 2.0.6 on 2018-09-01 17:34

from django.db import migrations, models
import django.db.models.deletion
import imageboard.models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31, unique=True)),
                ('slug', models.SlugField(max_length=31, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_number', models.PositiveIntegerField(default=imageboard.models.Thread.get_thread_number, unique=True)),
                ('subject', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(default='Anonymous', max_length=20)),
                ('time_made', models.DateTimeField(auto_now_add=True)),
                ('post', models.CharField(max_length=5000)),
                ('bumb_order', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('archived', models.BooleanField(default=False)),
                ('bumb_limit_reached', models.BooleanField(default=False)),
                ('reported', models.BooleanField(default=False)),
                ('image', sorl.thumbnail.fields.ImageField(upload_to='images')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='imageboard.Board')),
            ],
            options={
                'ordering': ['-bumb_order'],
            },
            bases=(models.Model, imageboard.models.DateMixin),
        ),
        migrations.CreateModel(
            name='UserPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_number', models.PositiveIntegerField(default=imageboard.models.UserPost.get_post_number, unique=True)),
                ('name', models.CharField(default='Anonymous', max_length=20)),
                ('time_made', models.DateTimeField(auto_now=True)),
                ('post', models.CharField(max_length=5000)),
                ('ip_address', models.GenericIPAddressField()),
                ('sage', models.BooleanField(default=False)),
                ('reported', models.BooleanField(default=False)),
                ('image', sorl.thumbnail.fields.ImageField(blank=True, upload_to='images')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='imageboard.Thread')),
            ],
            options={
                'ordering': ['post_number'],
            },
            bases=(models.Model, imageboard.models.DateMixin),
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['thread_number'], name='imageboard__thread__a71514_idx'),
        ),
    ]
