# Generated by Django 2.0.6 on 2018-11-20 18:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import embed_video.fields
import imageboard.models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=31, unique=True)),
                ('description', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=31, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thread_number', models.PositiveIntegerField(default=imageboard.models.Thread.get_thread_number, editable=False, unique=True)),
                ('subject', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(default='Anonymous', max_length=20)),
                ('time_made', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('post', models.CharField(max_length=5000)),
                ('bumb_order', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('archived', models.BooleanField(default=False)),
                ('bumb_limit_reached', models.BooleanField(default=False)),
                ('reported', models.BooleanField(default=False)),
                ('image', sorl.thumbnail.fields.ImageField(upload_to='images/')),
                ('pinned', models.BooleanField(default=False)),
                ('embed', embed_video.fields.EmbedVideoField(blank=True, help_text='Youtube, Vimeo or Soundcloud URL', null=True)),
                ('id_enabled', models.BooleanField(default=False, verbose_name='Enable poster IDs')),
                ('poster_id', models.CharField(blank=True, editable=False, max_length=30, null=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='imageboard.Board')),
            ],
            options={
                'ordering': ['-pinned', '-bumb_order'],
            },
            bases=(models.Model, imageboard.models.UtilityMixin),
        ),
        migrations.CreateModel(
            name='UserPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_number', models.PositiveIntegerField(default=imageboard.models.UserPost.get_post_number, editable=False, unique=True)),
                ('name', models.CharField(default='Anonymous', max_length=20)),
                ('time_made', models.DateTimeField(auto_now=True)),
                ('post', models.CharField(max_length=5000)),
                ('ip_address', models.GenericIPAddressField()),
                ('sage', models.BooleanField(default=False)),
                ('reported', models.BooleanField(default=False)),
                ('image', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='images/')),
                ('embed', embed_video.fields.EmbedVideoField(blank=True, help_text='Youtube, Vimeo or Soundcloud URL', null=True)),
                ('poster_id', models.CharField(editable=False, max_length=30, null=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='imageboard.Thread')),
            ],
            options={
                'ordering': ['post_number'],
            },
            bases=(models.Model, imageboard.models.UtilityMixin),
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['thread_number'], name='imageboard__thread__a71514_idx'),
        ),
    ]
