# Generated by Django 2.0.6 on 2018-07-01 14:54

from django.db import migrations, models
import imageboard.models


class Migration(migrations.Migration):

    dependencies = [
        ('imageboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thread',
            options={'get_latest_by': ['bumb_order']},
        ),
        migrations.AlterModelOptions(
            name='userpost',
            options={'ordering': ['-post_number']},
        ),
        migrations.AddField(
            model_name='thread',
            name='bumb_order',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='thread',
            name='name',
            field=models.CharField(default='Anonymous', max_length=20),
        ),
        migrations.AlterField(
            model_name='thread',
            name='subject',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='thread',
            name='thread_number',
            field=models.PositiveIntegerField(default=imageboard.models.Thread.get_thread_number, unique=True),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='name',
            field=models.CharField(default='Anonymous', max_length=20),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='post_number',
            field=models.PositiveIntegerField(default=imageboard.models.UserPost.get_post_number, unique=True),
        ),
    ]
