# Generated by Django 2.0.6 on 2018-06-29 13:12

from django.db import migrations, models
import imageboard.models


class Migration(migrations.Migration):

    dependencies = [
        ('imageboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='thread_number',
            field=models.PositiveIntegerField(default=imageboard.models.Thread.get_thread_number, unique=True),
        ),
    ]
