# Generated by Django 2.0.6 on 2018-09-01 18:20

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('imageboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='image',
            field=sorl.thumbnail.fields.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
