# Generated by Django 2.0.6 on 2018-07-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thread',
            options={'ordering': ['-bumb_order']},
        ),
        migrations.AlterModelOptions(
            name='userpost',
            options={'ordering': ['post_number']},
        ),
        migrations.AddField(
            model_name='thread',
            name='ip_address',
            field=models.GenericIPAddressField(default='127.0.0.1.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userpost',
            name='ip_address',
            field=models.GenericIPAddressField(default='127.0.0.1.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='thread',
            name='time_made',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
