# Generated by Django 2.0.6 on 2018-08-11 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageboard', '0002_userpost_sage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='bumb_order',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
