# Generated by Django 2.0.6 on 2018-06-29 13:28

from django.db import migrations, models
import imageboard.models


class Migration(migrations.Migration):

    dependencies = [
        ('imageboard', '0002_auto_20180629_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='name',
            field=models.CharField(default='Anonymous', max_length=20),
        ),
        migrations.AlterField(
            model_name='thread',
            name='subject',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='name',
            field=models.CharField(default='Anonymous', max_length=20),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='post_number',
            field=models.PositiveIntegerField(default=imageboard.models.UserPost.get_post_number, unique=True),
        ),
    ]
