# Generated by Django 2.0.6 on 2018-09-14 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageboard', '0002_auto_20180901_1820'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thread',
            options={'ordering': ['pinned', '-bumb_order']},
        ),
        migrations.AddField(
            model_name='thread',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
