# Generated by Django 2.0.6 on 2018-08-11 12:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('imageboard', '0003_auto_20180811_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='bumb_order',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 11, 12, 28, 55, 698820, tzinfo=utc)),
        ),
    ]
