# Generated by Django 2.0.6 on 2018-09-17 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageboard', '0003_auto_20180914_0753'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thread',
            options={'ordering': ['-pinned', '-bumb_order']},
        ),
        migrations.AddField(
            model_name='board',
            name='description',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
