# Generated by Django 2.0.6 on 2018-06-29 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageboard', '0003_auto_20180629_1328'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thread',
            options={'ordering': ['bumb_order']},
        ),
        migrations.AlterModelOptions(
            name='userpost',
            options={'ordering': ['-post_number']},
        ),
        migrations.AddField(
            model_name='thread',
            name='bumb_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
