# Generated by Django 2.0.6 on 2018-08-11 12:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('imageboard', '0004_auto_20180811_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='bumb_order',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
