# Generated by Django 2.0.6 on 2018-09-23 10:04

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('imageboard', '0004_auto_20180917_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userpost',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
