# Generated by Django 2.0.6 on 2018-08-12 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imageboard', '0006_auto_20180811_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='imageboard.Thread'),
        ),
    ]
