# Generated by Django 2.0.6 on 2018-08-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageboard', '0007_auto_20180812_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='bumb_limit_reached',
            field=models.BooleanField(default=False),
        ),
    ]
