# Generated by Django 2.0.6 on 2018-09-27 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageboard', '0007_auto_20180927_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='poster_id',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='thread',
            name='id_enabled',
            field=models.BooleanField(default=False, verbose_name='Enable poster IDs'),
        ),
    ]
