# Generated by Django 2.0.6 on 2018-10-02 17:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('imageboard', '0008_auto_20180927_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='poster_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='thread',
            name='time_made',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
