# Generated by Django 2.0.6 on 2018-08-14 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imageboard', '0008_thread_bumb_limit_reached'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='imageboard.Board'),
        ),
        migrations.AddIndex(
            model_name='thread',
            index=models.Index(fields=['thread_number'], name='imageboard__thread__a71514_idx'),
        ),
    ]
