# Generated by Django 2.0.6 on 2018-10-11 14:14

from django.db import migrations, models
import django.utils.timezone
import imageboard.models


class Migration(migrations.Migration):

    dependencies = [
        ('imageboard', '0009_auto_20181002_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='thread_number',
            field=models.PositiveIntegerField(default=imageboard.models.Thread.get_thread_number, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='thread',
            name='time_made',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
