# Generated by Django 2.0.6 on 2018-10-16 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageboard', '0010_auto_20181011_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='description',
            field=models.CharField(default='Nothing', max_length=300),
            preserve_default=False,
        ),
    ]
