# Generated by Django 2.0.6 on 2018-09-01 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imageboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transgression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('banned_until', models.DateTimeField()),
                ('reason', models.CharField(max_length=150)),
                ('global_ban', models.BooleanField(default=False)),
                ('banned_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='imageboard.Board')),
            ],
        ),
    ]
