# Generated by Django 2.0.6 on 2018-07-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transgression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('banned_until', models.DateTimeField()),
                ('reason', models.CharField(max_length=150)),
            ],
        ),
    ]
