# Generated by Django 2.0.6 on 2018-09-23 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transgression',
            name='banned_until',
            field=models.DateTimeField(help_text='Format: YYYY-MM-DD hh:mm. Eg. 2049-12-24 18:05'),
        ),
    ]
